name: Generate pacman animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate Pac-Man contribution graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: oran-gabi

      - name: Commit generated graph
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update pacman contribution graph"
          file_pattern: "*.svg"
