name: Update Trophies

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual trigger

jobs:
  update-trophies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Trophies
        uses: soulteary/profile-trophy-action@v1.0.0
        with:
          options: 'username=oran-gabi&theme=radical&no-bg=true&no-frame=false&margin-w=4'
          path: trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add trophy.svg
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update GitHub trophies" && git push)
